// <auto-generated />
using System;
using AssetManagement.Infrastrucuture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Infrastrucuture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedVehicleId")
                        .IsUnique()
                        .HasFilter("[AssignedVehicleId] IS NOT NULL");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.DriverCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverCertifications");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.InspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastInspection")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextInspection")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("InspectionRecords");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInCharge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("901b2c5e-fc7a-441b-9d79-4940b60b69cc"),
                            ContactInCharge = "John Doe",
                            CostCenter = "Fleet Management",
                            DivisionName = "Devision 1",
                            LocationName = "Main Garage",
                            ProjectName = "Fleet Management"
                        },
                        new
                        {
                            Id = new Guid("8346b56d-d507-4dd7-99ba-3a17881cc642"),
                            ContactInCharge = "Jane Smith",
                            CostCenter = "Logistics",
                            DivisionName = "Devision 1",
                            LocationName = "East Warehouse",
                            ProjectName = "Logistics"
                        },
                        new
                        {
                            Id = new Guid("441d36b4-dfcd-4817-afe1-27a67a1b218c"),
                            ContactInCharge = "Michael Brown",
                            CostCenter = "Construction",
                            DivisionName = "Devision 1",
                            LocationName = "North Yard",
                            ProjectName = "Construction"
                        },
                        new
                        {
                            Id = new Guid("6fa5b8c6-6f12-4ace-8232-2c06454b64a1"),
                            ContactInCharge = "Emily Davis",
                            CostCenter = "Distribution",
                            DivisionName = "Devision 1",
                            LocationName = "West Depot",
                            ProjectName = "Distribution"
                        },
                        new
                        {
                            Id = new Guid("8733e63f-6446-4b91-b7b6-744a8cfcf75e"),
                            ContactInCharge = "Robert Wilson",
                            CostCenter = "Transport Hub",
                            DivisionName = "Devision 1",
                            LocationName = "South Terminal",
                            ProjectName = "Transport Hub"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermitHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.SafetyEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("SafetyEquipments");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Co2Emission")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedEndTermValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FuelCapacity")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GpsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastInspection")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaintenanceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NextInspection")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SteeringType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ModelId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.VehicleBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDivision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9497f582-8512-443f-a457-0fb2b807656a"),
                            Category = "Howo",
                            Division = "T5G",
                            Name = "Sinotruk",
                            SubDivision = "Heavy Trucks"
                        },
                        new
                        {
                            Id = new Guid("9497f582-8512-443f-a457-0fb2b807656b"),
                            Category = "Sedan",
                            Division = "Camry",
                            Name = "Toyota",
                            SubDivision = "Hybrid"
                        },
                        new
                        {
                            Id = new Guid("1885aa2b-fd41-475b-863a-d55efca9f4d3"),
                            Category = "SUV",
                            Division = "Explorer",
                            Name = "Ford",
                            SubDivision = "XLT"
                        },
                        new
                        {
                            Id = new Guid("66694f49-8e27-4b78-8233-57f59b9b5036"),
                            Category = "Electric",
                            Division = "Model S",
                            Name = "Tesla",
                            SubDivision = "Plaid"
                        },
                        new
                        {
                            Id = new Guid("a479fb2c-b478-441a-b950-11635ac696a7"),
                            Category = "Compact",
                            Division = "Civic",
                            Name = "Honda",
                            SubDivision = "Sport"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f17a7c8d-4a3b-4b81-b1e6-8d97b0f1a8c9"),
                            BrandId = new Guid("9497f582-8512-443f-a457-0fb2b807656b"),
                            ModelName = "Corolla",
                            ModelYear = 2023
                        },
                        new
                        {
                            Id = new Guid("d91e3b7a-5c8e-4f72-a4d7-6c92b3d8a7e9"),
                            BrandId = new Guid("a479fb2c-b478-441a-b950-11635ac696a7"),
                            ModelName = "Civic",
                            ModelYear = 2022
                        },
                        new
                        {
                            Id = new Guid("e8b2c7d6-3a9e-4b5f-bd17-2f3c9a7e6b8a"),
                            BrandId = new Guid("1885aa2b-fd41-475b-863a-d55efca9f4d3"),
                            ModelName = "F-150",
                            ModelYear = 2024
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99e315c4-395d-4a32-9342-874f13628ebf"),
                            Category = "Light Vehicles",
                            Division = "Transport",
                            TypeName = "Pickup"
                        },
                        new
                        {
                            Id = new Guid("67f85360-095e-4f42-ac74-1f7790084237"),
                            Category = "Passenger Vehicles",
                            Division = "City Transport",
                            TypeName = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("8d8f6f0b-dd69-478e-9f6e-66ba77908a6d"),
                            Category = "Off-Road Vehicles",
                            Division = "All-Terrain",
                            TypeName = "SUV"
                        },
                        new
                        {
                            Id = new Guid("8c1b774d-ef82-4c92-bb69-e3a62d8b260b"),
                            Category = "Eco-Friendly",
                            Division = "Sustainable Mobility",
                            TypeName = "Electric"
                        },
                        new
                        {
                            Id = new Guid("37bab96f-8fd9-4d67-b61e-e593b2d0d8ec"),
                            Category = "Heavy Duty",
                            Division = "Industrial Transport",
                            TypeName = "Truck"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Driver", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Vehicle", "AssignedVehicle")
                        .WithOne("AssignedDriver")
                        .HasForeignKey("AssetManagement.Domain.Entities.Driver", "AssignedVehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedVehicle");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.DriverCertification", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Driver", "Driver")
                        .WithMany("Certifications")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.InspectionRecord", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Permit", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Vehicle", null)
                        .WithMany("Permits")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.SafetyEquipment", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("SafetyEquipments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.VehicleBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.VehicleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Location");

                    b.Navigation("Model");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.VehicleBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("AssignedDriver")
                        .IsRequired();

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Permits");

                    b.Navigation("SafetyEquipments");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.VehicleBrand", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
